version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped

  backend:
    build: .
    container_name: dsci560-backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - PROVIDER=${PROVIDER:-oss}
      - HF_EMBED_MODEL=${HF_EMBED_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - TEMP=${TEMP:-0.0}
      - PERSIST_DIR=/data/vectorstore/faiss
      - UPLOAD_DIR=/data/uploads
      - SQLITE_DB_PATH=/data/ads_texts.db
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://localhost:3000","http://127.0.0.1:3000","http://frontend:3000"]}
    volumes:
      - ./data:/data
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: dsci560-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: unless-stopped
